## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CommandLine
        run: sed -i 's/ PublicIp,//' ip.txt
      - name: CommandLine2
        run: ls
      - name: CommandLine3
        run: cat ip.txt
