## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CommandLine
        run: |
         sed -i 's/PublicIp//g' ip.txt
         sed -i 's/"//g' ip.txt
         sed -i 's/://g' ip.txt
      - name: CommandLine2
        run: ls
      - name: CommandLine3
        run: |
         cat ip.txt
         ip=$( cat ip.txt )
      - name: CommandLine4
        run: echo "$ip"
