## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

env:
  VARNAME: $VARNAME

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CommandLine
        run: |
         sed -i 's/PublicIp//g' ip.txt
         sed -i 's/"//g' ip.txt
         sed -i 's/://g' ip.txt
      - name: CommandLine2
        run: ls
      - name: CommandLine3
        run: |
         ip=$(<ip.txt)
         echo $ip
         export VARNAME="Hello, World!"
         printenv
         ip=$ip
         sed -i 's/#{IP}/$VARNAME/g' ip.json
         cat ip.json
